In [9]:
import pandas as pd

In [10]:
data = pd.read_csv("patents.csv")

In [11]:
data.head()

,publication_number,doc_id,flag_patent,publication_date,appnum,grp_ml,grp_evo,grp_nlp,grp_speech,grp_vision,grp_kr,grp_planning,grp_hardware
0,US-RE28686-E,RE28686,1,19760120,5505609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l2
1,US-2017169084-A9,20170169084,0,20170615,15037180,NaN,NaN,NaN,NaN,l1,l1,l1,l1
2,US-2018128598-A9,20180128598,0,20180510,15458673,NaN,NaN,NaN,NaN,l1,NaN,NaN,NaN
3,US-4078721-A,4078721,1,19780314,5721690,NaN,NaN,NaN,NaN,NaN,NaN,l1,NaN
4,US-4051524-A,4051524,1,19770927,5684145,NaN,NaN,NaN,l2,l2,NaN,l2,NaN

In [12]:
for g in data.columns:
    print(f'{g}:')
    print(f'seed:')
    print(len(data.loc[data[g].isin(['seed'])]))
    print(len(data.loc[data[g].isin(['antiseed'])]))

publication_number:
seed:
0
0
doc_id:
seed:
0
0
flag_patent:
seed:
0
0
publication_date:
seed:
0
0
appnum:
seed:
0
0
grp_ml:
seed:
959
15000
grp_evo:
seed:
82

/home/kangel/.local/lib/python3.9/site-packages/numpy/lib/arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

15000
grp_nlp:
seed:
1084
15000
grp_speech:
seed:
763
15000
grp_vision:
seed:
803
15000
grp_kr:
seed:
661
15000
grp_planning:
seed:
1451
15000
grp_hardware:
seed:
2659
15000

In [13]:
filtered = data.loc[data['grp_ml'].isin(['seed']) | data['grp_ml'].isin(['antiseed'])]

In [14]:
filtered.loc[filtered['grp_ml']=='seed']

,publication_number,doc_id,flag_patent,publication_date,appnum,grp_ml,grp_evo,grp_nlp,grp_speech,grp_vision,grp_kr,grp_planning,grp_hardware
1312,US-2017052060-A1,20170052060,0,20170223,15306472,seed,l1,NaN,NaN,l1,l1,l1,l1
2719,US-2016086087-A1,20160086087,0,20160324,14491373,seed,NaN,l1,l1,l1,l1,NaN,seed
3732,US-2013085972-A1,20130085972,0,20130404,13687192,seed,NaN,l1,l1,l1,l1,l1,seed
6071,US-2017293859-A1,20170293859,0,20171012,15472363,seed,l1,NaN,NaN,NaN,l1,l1,l1
13201,US-2004162796-A1,20040162796,0,20040819,10748631,seed,l2,l2,l2,l1,l2,l1,seed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2211564,US-2014019392-A1,20140019392,0,20140116,13829919,seed,l2,l1,l1,l1,l1,l1,seed
2212534,US-2014250039-A1,20140250039,0,20140904,13587424,seed,l2,l2,l2,l1,l2,l1,seed
2219858,US-9852373-B2,9852373,1,20171226,14727630,seed,l1,NaN,NaN,l1,l1,l1,l1
2221411,US-7356518-B2,7356518,1,20080408,10922777,seed,seed,l2,l2,l1,l1,l1,l1
2221460,US-8521669-B2,8521669,1,20130827,12789502,seed,NaN,NaN,NaN,l1,l1,l1,l1

In [15]:
filtered.sort_values('publication_date')

,publication_number,doc_id,flag_patent,publication_date,appnum,grp_ml,grp_evo,grp_nlp,grp_speech,grp_vision,grp_kr,grp_planning,grp_hardware
1676385,US-3933865-A,3933865,1,19760120,5541317,antiseed,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966334,US-3937488-A,3937488,1,19760210,5444637,antiseed,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314922,US-3939360-A,3939360,1,19760217,5543193,antiseed,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1949697,US-3949508-A,3949508,1,19760413,5478083,antiseed,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1106329,US-3953561-A,3953561,1,19760427,5551003,antiseed,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592135,US-10143499-B2,10143499,1,20181204,14509252,antiseed,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1942536,US-10159284-B2,10159284,1,20181225,15316435,antiseed,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721742,US-10161628-B2,10161628,1,20181225,14786596,antiseed,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2099927,US-10161025-B2,10161025,1,20181225,14690239,antiseed,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1079766,US-10162824-B2,10162824,1,20181225,15451004,antiseed,NaN,NaN,l1,NaN,l1,NaN,NaN

In [16]:
antiseeds = filtered.loc[filtered['grp_ml']=='antiseed']
seeds = filtered.loc[filtered['grp_ml']=='seed']

In [17]:
seeds = seeds.sample(900)
antiseeds = antiseeds.sample(900)

In [18]:
#whole_sample = pd.concat([seeds, antiseeds], axis = 0)

In [19]:
# whole_sample

In [20]:
seed_ids = seeds['doc_id'].to_list()
antiseed_ids = antiseeds['doc_id'].to_list()

In [22]:
# with open('ids.txt','w') as f:
#     for id in ids:
#         f.write(str(id)+'\n')
with open('seeds_ids.txt','w') as f:
    for id in seed_ids:
        f.write(str(id)+'\n')
with open('antiseeds_ids.txt','w') as f:
    for id in antiseed_ids:
        f.write(str(id)+'\n')

In [25]:
# whole_sample.to_csv('sample.csv', index=False)
seeds.loc[seeds['doc_id']=='20160155049']

,publication_number,doc_id,flag_patent,publication_date,appnum,grp_ml,grp_evo,grp_nlp,grp_speech,grp_vision,grp_kr,grp_planning,grp_hardware
1800416,US-2016155049-A1,20160155049,0,20160602,14704785,seed,NaN,NaN,l1,l1,NaN,l1,l1